FROM rocm/pytorch:rocm7.2_ubuntu22.04_py3.10_pytorch_release_2.9.1

# Install dependencies
RUN pip install ultralytics

# Installing headless version of OpenCV
RUN pip uninstall opencv-python -y
RUN pip install opencv-python-headless
